{
 "title": "grafana/graphite/statsd",
 "description": "Dashboards for the dashboards",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "creates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "alias(sumSeries(carbon.agents.*.creates), 'creates')"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "target": "alias(sumSeries(carbon.agents.*.cpuUsage), 'CPU usage')"
    }
   ]
  },
  {
   "title": "total # of stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "target": "alias(statsd.*, 'total # of stats overall')"
    }
   ]
  },
  {
   "title": "errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "alias(sumSeries(carbon.agents.*.errors), 'errors')"
    }
   ]
  },
  {
   "title": "Dropped stat creations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "targets": [
    {
     "target": "alias(sumSeries(carbon.agents.*.droppedCreates), 'dropped creates')"
    }
   ]
  },
  {
   "title": "aggregator memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(sumSeries(carbon.aggregator.*.memUsage), 'CPU usage')"
    }
   ]
  },
  {
   "title": "statsd flush time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "alias(movingAverage(stats.statsd.graphiteStats.flush_time, '2hour'), 'flush_time')"
    }
   ]
  }
 ]
}