{
 "title": "hack.af",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "production,development" }
  ]
 },
 "panels": [
  {
   "title": "Endpoint latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(stats.timers.$environment.hackaf.http.response.*.mean, 6)"
    }
   ]
  },
  {
   "title": "HTTP error codes across all endpoints",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "target": "groupByNode(*.$environment.hackaf.http.response.*.*, 6, 'average')"
    }
   ]
  },
  {
   "title": "HTTP error codes by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "target": "aliasByNode(*.$environment.hackaf.http.response.*.*, 5, 6)"
    }
   ]
  }
 ]
}