{
 "title": "scrappy",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "All stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasByNode(stats.production.scrappy.success.*, 3, 4)"
    }
   ]
  },
  {
   "title": "All errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "aliasByNode(stats.production.scrappy.errors.*, 3, 4)"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "alias(transformNull(asPercent(#C, #A), 100), '% successful traffic')",
     "targetFull": "alias(transformNull(asPercent(diffSeries(alias(sumSeries(aliasByNode(stats.production.scrappy.*.*, 4)), 'total'), alias(sumSeries(aliasByNode(stats.production.scrappy.errors.*, 4)), 'errors')), alias(sumSeries(aliasByNode(stats.production.scrappy.*.*, 4)), 'total')), 100), '% successful traffic')"
    }
   ]
  }
 ]
}