{
 "title": "sinerider-reddit-bot",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "development,staging,production" }
  ]
 },
 "panels": [
  {
   "title": "HTTP error codes by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasByNode(*.$environment.sinerider-reddit-bot.web.http.response.*.*, 6, 7)"
    }
   ]
  },
  {
   "title": "Endpoint latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(*.timers.$environment.sinerider-reddit-bot.web.http.response.*.mean, 7)"
    }
   ]
  },
  {
   "title": "Reddit Command Executions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "aliasByNode(*.$environment.sinerider-reddit-bot.command, 5)"
    }
   ]
  },
  {
   "title": "Reddit Poll Worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "targets": [
    {
     "target": "aliasByNode(stats.$environment.sinerider-reddit-bot.worker.poll.*, 5)"
    }
   ]
  }
 ]
}