{
 "title": "sinerider-api",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "production,development" }
  ]
 },
 "panels": [
  {
   "title": "HTTP error codes by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasByNode(*.$environment.sinerider-api.http.response.*.*, 5, 6)"
    }
   ]
  },
  {
   "title": "HTTP error codes across all endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "target": "groupByNode(*.$environment.sinerider-api.http.response.*.*, 6, 'sum')"
    }
   ]
  },
  {
   "title": "Endpoint latencies",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(*.timers.$environment.sinerider-api.http.response.*.mean, 6)"
    }
   ]
  }
 ]
}