{
 "title": "sinerider-twitter-bot",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "production,development" }
  ]
 },
 "panels": [
  { "title": "Batch Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Refresh tokens",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "aliasByNode(stats.$environment.sinerider-twitter-bot.worker.tokens.refresh.*, 6)"
    }
   ]
  },
  {
   "title": "Query twitter submissions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "target": "aliasByNode(stats.$environment.sinerider-twitter-bot.worker.twitter.submissions.query.*, 7)"
    }
   ]
  },
  {
   "title": "Query twitter submissions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "target": "aliasByNode(stats.$environment.sinerider-twitter-bot.worker.workqueue.*, 5)"
    }
   ]
  },
  { "title": "Web Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "HTTP error codes by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "aliasByNode(stats.$environment.sinerider-twitter-bot.web.http.response.*.*, 6, 7)"
    }
   ]
  },
  {
   "title": "HTTP latencies by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(stats.timers.$environment.sinerider-twitter-bot.web.http.response.*.mean, 7)"
    }
   ]
  }
 ]
}