{
 "title": "sinerider-scoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "production,development" }
  ]
 },
 "panels": [
  {
   "title": "HTTP latencies by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(stats.timers.$environment.sinerider-scoring.http.response.*.mean, 6)"
    }
   ]
  },
  {
   "title": "HTTP error codes by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 0 },
   "targets": [
    {
     "target": "aliasByNode(stats.$environment.sinerider-scoring.http.response.*.*, 5, 6)"
    }
   ]
  },
  {
   "title": "Game execution statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "target": "aliasByNode(stats.$environment.sinerider-scoring.game.execute.*, 4, 5)"
    }
   ]
  },
  {
   "title": "Level simulation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(stats.timers.$environment.sinerider-scoring.game.simulate.time.mean, 5)"
    }
   ]
  },
  {
   "title": "Game level simulation statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "target": "aliasByNode(stats.$environment.sinerider-scoring.game.simulate.*, 4, 6)"
    }
   ]
  },
  {
   "title": "# of cloudinary uploads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "aliasByNode(stats.$environment.sinerider-scoring.cloudinary.upload.*, 5, 6)"
    }
   ]
  },
  {
   "title": "Cloudinary upload latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(stats.timers.$environment.sinerider-scoring.cloudinary.upload.time.mean, 5, 6)"
    }
   ]
  }
 ]
}