{
 "title": "slash-z",
 "tags": [ "service" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "staging,production" }
  ]
 },
 "panels": [
  {
   "title": "Zoom API http error codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasByNode(stats.$env.slashz.zoom.http.code.*.*, 6, 7)"
    }
   ]
  },
  {
   "title": "Zoom License Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(asPercent(#D, #A), 'zoom license utilization %')",
     "targetFull": "alias(asPercent(alias(diffSeries(alias(stats.gauges.$env.slashz.hosts.total, 'total'), alias(stats.gauges.$env.slashz.hosts.open, 'open')), 'used'), alias(stats.gauges.$env.slashz.hosts.total, 'total')), 'zoom license utilization %')"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "description": "The number of people active in a zoom call created by slashz",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "target": "stats.gauges.$env.slashz.app.active_users"
    }
   ]
  },
  {
   "title": "Zoom API http error codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "groupByNode(stats.$env.slashz.zoom.http.code.*.*, 7)"
    }
   ]
  },
  {
   "title": "Response codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "groupByNode(stats.$env.slashz.http.response.*.*, 6, 'average')"
    }
   ]
  },
  {
   "title": "Zoom License Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "alias(asPercent(#D, #A), 'zoom license utilization %')",
     "targetFull": "alias(asPercent(alias(diffSeries(alias(stats.gauges.$env.slashz.hosts.total, 'total'), alias(stats.gauges.$env.slashz.hosts.open, 'open')), 'used'), alias(stats.gauges.$env.slashz.hosts.total, 'total')), 'zoom license utilization %')"
    }
   ]
  },
  {
   "title": "Zoom License Utilization (RAW)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(stats.gauges.$env.slashz.hosts.total, 'total')"
    },
    {
     "target": "alias(stats.gauges.$env.slashz.hosts.open, 'open')"
    },
    {
     "target": "alias(diffSeries(#A, #C), 'used')",
     "targetFull": "alias(diffSeries(alias(stats.gauges.$env.slashz.hosts.total, 'total'), alias(stats.gauges.$env.slashz.hosts.open, 'open')), 'used')"
    }
   ]
  },
  {
   "title": "Endpoint latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(stats.timers.$env.slashz.http.response.*.mean, 6)"
    }
   ]
  },
  {
   "title": "All errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "targets": [
    {
     "target": "aliasByNode(stats.$env.slashz.error.*, 4)"
    }
   ]
  },
  {
   "title": "Meeting deletion error codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(asPercent(stats.$env.slashz.delete_meeting.*, #B), 4)",
     "targetFull": "aliasByNode(asPercent(stats.$env.slashz.delete_meeting.*, alias(sumSeries(stats.$env.slashz.delete_meeting.*), 'total')), 4)"
    }
   ]
  },
  {
   "title": "HTTP error code ratios",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "groupByNode(stats.$env.slashz.http.response.*.*, 6, 'average')"
    }
   ]
  }
 ]
}